### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by Tobe2d** [Sharrnah/whispering#9]
When I start Whispering Tiger.exe I get this:

![image](https://user-images.githubusercontent.com/4099839/227651704-76d2a42d-ea01-46ff-9784-bc3784d9b68b.png)

And when click on update it give me this error:
![image](https://user-images.githubusercontent.com/4099839/227651740-6c0cba27-c86c-41af-83c5-14be99bcbe97.png)

 When I clock OK i get this screen and it stay for ever:
 
![image](https://user-images.githubusercontent.com/4099839/227652127-c38d968f-50b8-4e14-baf7-92d073d1ec11.png)

**Comment by Sharrnah** [comment]
That looks like you can't access the download server for some reason.
I will see to have it try others server in this case as well.

**Comment by Sharrnah** [comment]
@Tobe2d Can you try if you can reach one of these URLs in general?
EU: https://eu2.contabostorage.com/bf1a89517e2643359087e5d8219c0c67:projects/whispering/whispering-tiger1.3.3.1_win.zip
US: https://usc1.contabostorage.com/8fcf133c506f4e688c7ab9ad537b5c18:projects/whispering/whispering-tiger1.3.3.1_win.zip

If you can download it manually, you can also just do this:
- after downloading, extract it where the UI executable is.
- Run the UI executable
- When it asks to Update, press "No".

Since the UI does not know which version you extracted, it will write the newest version infos into the directory, so it won't ask again to update until a new version is available.

**Comment by Sharrnah** [comment]
Just as info. i released Updates for the UI and the Python backend. (I already updated the links above. US is still uploading, but should be finished soon.)

The UI also includes the retry+server fallback on every network error. I hope that helps in this case. Even though i doubt it.

it could also be that the firewall is blocking the application. Can't do much about it in this case.

**Comment by Tobe2d** [comment]
it work with direct link you added above nut not solved it as you expected ;-)
Thanks a lot for helping.
